<?php

function uc_quadriga_debug($contents) {
  $file = dirname(__FILE__)."/".'log.txt';
  file_put_contents($file, date('m-d H:i:s').": ", FILE_APPEND);
  if (is_array($contents))
    file_put_contents($file, var_export($contents, true)."\r\n", FILE_APPEND);    
  else if (is_object($contents))
    file_put_contents($file, json_encode($contents)."\r\n", FILE_APPEND);
  else
    file_put_contents($file, $contents."\r\n", FILE_APPEND);
}

function uc_quadriga_menu() {
  $items['cart/quadriga/complete'] = array(
    'title' => 'Payment complete',
    'page callback' => 'uc_quadriga_complete',
    'access callback' => 'uc_quadriga_completion_access',
    'type' => MENU_CALLBACK,
    'file' => 'uc_quadriga.pages.inc',
  );
  $items['cart/quadriga/failed'] = array(
    'title' => 'Payment failed',
    'page callback' => 'uc_quadriga_failed',
    'access callback' => 'uc_quadriga_completion_access',
    'type' => MENU_CALLBACK,
    'file' => 'uc_quadriga.pages.inc',
  );

  return $items;
}

function uc_quadriga_completion_access() {
  return TRUE;
}

function uc_quadriga_ucga_display() {
  if (arg(0) == 'cart' && arg(1) == 'quadriga' && arg(2) == 'complete') {
    return TRUE;
  }
}

function uc_quadriga_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'uc_cart_checkout_review_form' && ($order_id = intval($_SESSION['cart_order'])) > 0) {
    $order = uc_order_load($order_id);

    if ($order->payment_method == 'quadriga') {
      unset($form['actions']['submit']);
      $formToGet = drupal_get_form('uc_quadriga_form', $order);
      //debug($form);
      //$form['#prefix'] = '<table style="display: inline; padding-top: 1em;"><tr><td>';
      //$form['#suffix'] = '</td><td>'. render(drupal_get_form('uc_quadriga_form', $order)) .'</td></tr></table>';
      $form['#suffix'] = render($formToGet) ;
    }
  }
}

function uc_quadriga_uc_payment_method() {
  $path = base_path() . drupal_get_path('module', 'uc_quadriga');
  $title = variable_get('uc_quadriga_method_title', t('QuadrigaCX'));
  $methods[] = array(
    'id' => 'quadriga',
    'name' => t('QuadrigaCX'),
    'title' => $title,
    'review' => "QuadrigaCX",
    'desc' => t('Redirect to QuadrigaCX payment gate.'),
    'callback' => 'uc_payment_method_quadriga',
    'weight' => 3,
    'checkout' => TRUE,
    'no_gateway' => TRUE,
  );
  return $methods;
}

function uc_payment_method_quadriga($op, &$arg1) {
  switch ($op) {
    case 'cart-details':
      return;

    case 'cart-process':
      return;

    case 'settings':
      $form['#prefix'] = '<p>
        Remember to update the Callback URL address at QuadrigaCX in your <a href="https://www.quadrigacx.com/merchant_setup" target="_blank">Merchant Setup page</a>.
        <br/><code>'.url('cart/quadriga/complete', array('absolute' => TRUE)) . '/index.php'.'</code>
      </p>';
      $form['uc_quadriga_merchant_key'] = array(
        '#type' => 'textfield',
        '#title' => t('QuadrigaCX Store Key'),
        '#description' => t('Your QuadrigaCX Store Key.  (Looks something like this: x3ehw82gudebhct7cjfxbynyhfd67ch)'),
        '#default_value' => variable_get('uc_quadriga_merchant_key', ''),
        '#size' => 40,
      );
      $form['uc_quadriga_method_title'] = array(
        '#type' => 'textfield',
        '#title' => t('Payment method title'),
        '#default_value' => variable_get('uc_quadriga_method_title', t('Pay with Bitcoins via QuadrigaCX')),
      );
      $form['uc_quadriga_checkout_button'] = array(
        '#type' => 'textfield',
        '#title' => t('Order review submit button text'),
        '#description' => t('Provide specific text for the submit button on the order review page.'),
        '#default_value' => variable_get('uc_quadriga_checkout_button', t('Submit Order')),
      );
      return $form;
  }
}

function uc_get_hash_for_order( $order ) {
  return md5(variable_get('uc_quadriga_merchant_key', '') . $order->order_id . $order->order_total);
}

function uc_quadriga_form($form_id, $form_state) {
  $order = $form_state['build_info']['args'][0];
  $country = uc_get_country_data(array('country_id' => $order->billing_country));
  if ($country === FALSE) {
    $country = array(0 => array('country_iso_code_3' => 'CAN'));
  }
  $context = array(
    'revision' => 'formatted-original',
    'location' => 'QuadrigaCX-form',
  );
  $options = array(
    'sign' => FALSE,
    'dec' => '.',
    'thou' => FALSE,
  );
  
  $data = array(
    "key" => variable_get('uc_quadriga_merchant_key', ''),
    "currency" => strtolower(variable_get("uc_currency_code", "USD")),
    "uc_order" => $order->order_id,
    "amount" => $order->order_total,
    "hash_quadriga" => uc_get_hash_for_order($order),
  );
  $data["custom"] = implode(",", array_diff(array_keys($data), array("currency", "amount", "key")));
  
  $form['#action'] = 'https://www.quadrigacx.com/merchant';
  $form['#method'] = 'POST';

  foreach ($data as $name => $value) {
    $form[$name] = array('#type' => 'hidden', '#value' => $value);
  }

  $form['actions'] = array(
    '#type' => 'actions',
    'back' => array(
      '#type' => 'submit',
      '#value' => variable_get('uc_quadriga_checkout_button', t('Submit Order')),
    ),
  );

  return $form;
}
